FROM ghcr.io/tauffer-consulting/domino-base-piece:latest

RUN pip install --no-cache-dir "domino-py[cli]>=0.9.0"

WORKDIR /app

# Bake the sampled NIfTI data into the image
COPY dependencies/condist-fl-trainer/data_sampled /data

# Copy Domino metadata
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino
